name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MySQL
      # You may pin to the exact commit or the version.
      # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:        
        # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql root password: 'TestPass123!'
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: 'TestDatabase'
    - name: Set secrets
      run: dotnet user-secrets set 'ConnectionStrings:ModelDb' 'server=localhost;database=TestDatabase;user=root;password=TestPass123!' --project iRLeagueApiCore.UnitTests
    #- name: Grant user access
    #  run: mysql -u 'testuser' -p 'TestPass123!' < GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%';
    - name: Add Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/SSchulze1989/index.json --username SSchulze1989 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
