name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_DATABSE: TestDatabase
      DB_USER: testuser
      DB_PASSWORD: TestPass123!

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MySQL
      # You may pin to the exact commit or the version.
      # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:
       # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: ${{ env.DB_USER }}
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: ${{ env.DB_PASSWORD }}
    - name: Create Database
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u ${{ env.DB_USER }} -p ${{ env.DB_PASSWORD }}
    - name: Update Nuget Source
      run: dotnet nuget update source github --username SSchulze1989 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
